"""
Intelligence: Weekly YouTube Niche Intelligence

Collects competitor channel data, classifies thumbnails via Gemini Vision,
runs 8 analytical dimensions, and generates a branded 16-slide PPTX report.

Usage:
    PYTHONIOENCODING=utf-8 python tools/intelligence/intelligence.py

Flags:
    --skip-vision     Skip Gemini thumbnail classification (faster, no Vision cost)
    --skip-comments   Skip comment collection
    --days N          Look back N days for videos (default: 30)
"""

import argparse
import sys
import os
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from tools.utils import get_env, log_cost
from tools.intelligence import collector, vision, analyzer, db, slide_builder

# --------------------------------------------------------------------------- #
# Paths
# --------------------------------------------------------------------------- #

PROJECT_ROOT = Path(__file__).parent.parent.parent
INTEL_DIR = PROJECT_ROOT / "outputs" / "intelligence"
DB_PATH = INTEL_DIR / "intelligence.db"
THUMB_DIR = INTEL_DIR / "thumbnails"


def _week_label() -> str:
    now = datetime.now(timezone.utc)
    return f"{now.year}-W{now.isocalendar()[1]:02d}"


def _write_tag_signals(results: dict, week_label: str, intel_dir: Path) -> Path:
    """Emit a single-word tag-signals MD sidecar for Agent 8 to consume."""
    from collections import Counter

    # Top competitor tags: `videos[*].tags` is a list (YouTube API shape); keep single-word entries.
    raw_tag_counter: Counter = Counter()
    for v in results.get("videos", []):
        tags = v.get("tags") or []
        if isinstance(tags, str):
            tags = [t for t in tags.split(",")]
        for raw in tags:
            tag = (raw or "").strip().lower()
            if tag and " " not in tag and "-" not in tag and len(tag) > 2:
                raw_tag_counter[tag] += 1
    top_tags = [t for t, _ in raw_tag_counter.most_common(30)]

    # Trending title words + emotional triggers — both already Counters from analyzer.
    top_topics = [
        w for w, _ in results.get("trending_topics", Counter()).most_common(40)
        if " " not in w
    ][:20]
    top_title = [
        w for w, _ in results.get("title_words", Counter()).most_common(40)
        if " " not in w
    ][:20]

    # Content gaps: list[dict] with `topic` already single-word.
    gap_topics = [g["topic"] for g in results.get("gaps", []) if g.get("topic")][:10]

    lines = [
        f"# Niche Tag Signals — {week_label}",
        f"_Generated by Agent 11 · For consumption by Agent 8 · {datetime.now(timezone.utc).date().isoformat()}_",
        "",
        "## Top Trending Tags (from competitor videos, single-word, top 30)",
        *[f"- {t}" for t in top_tags],
        "",
        "## Top Trending Title Topics (single-word, top 20)",
        *[f"- {t}" for t in top_topics],
        "",
        "## Top Title Words (emotional triggers, stop-word filtered, top 20)",
        *[f"- {t}" for t in top_title],
        "",
        "## Content Gaps (high-engagement single-word topics SENSUM hasn't covered)",
        *[f"- {t}" for t in gap_topics],
        "",
    ]

    path = intel_dir / f"{week_label}_tag_signals.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


# --------------------------------------------------------------------------- #
# Main pipeline
# --------------------------------------------------------------------------- #

def run(skip_vision: bool = False, skip_comments: bool = False, days: int = 30):
    INTEL_DIR.mkdir(parents=True, exist_ok=True)
    THUMB_DIR.mkdir(parents=True, exist_ok=True)

    api_key = get_env("YOUTUBE_API_KEY")
    sensum_id = get_env("SENSUM_CHANNEL_ID")
    project = get_env("GOOGLE_CLOUD_PROJECT")
    week_label = _week_label()

    print(f"\n{'='*60}")
    print(f"  SENSUM Niche Intelligence — {week_label}")
    print(f"{'='*60}\n")

    # ------------------------------------------------------------------ #
    # Step 1 — Init DB
    # ------------------------------------------------------------------ #
    print("[1/7] Initialising database...")
    db.init_db(DB_PATH)

    # ------------------------------------------------------------------ #
    # Step 2 — Discover channels
    # ------------------------------------------------------------------ #
    print("[2/7] Discovering competitor channels...")
    channel_ids = collector.discover_channels(api_key)
    channel_ids.add(sensum_id)
    print(f"  Found {len(channel_ids)} channels (incl. SENSUM).")

    # ------------------------------------------------------------------ #
    # Step 3 — Fetch channel stats + recent videos
    # ------------------------------------------------------------------ #
    print(f"[3/7] Fetching channel stats and last {days} days of videos...")
    channels = collector.fetch_channel_stats(api_key, list(channel_ids), sensum_id)
    print(f"  Retrieved stats for {len(channels)} channels.")

    all_videos: list[dict] = []
    for i, cid in enumerate(channel_ids, 1):
        if i % 10 == 0:
            print(f"  Fetching videos: {i}/{len(channel_ids)} channels...")
        vids = collector.fetch_recent_videos(api_key, cid, days=days)
        all_videos.extend(vids)

    print(f"  Collected {len(all_videos)} videos across all channels.")

    # ------------------------------------------------------------------ #
    # Step 4 — Comments
    # ------------------------------------------------------------------ #
    comments: list[dict] = []
    if not skip_comments:
        print("[4/7] Fetching comments for top videos by view velocity...")
        velocities = analyzer.view_velocity(all_videos)
        top_ids = [v["video_id"] for v in velocities[:20]]
        comments = collector.fetch_comments(api_key, top_ids)
        print(f"  Collected {len(comments)} comments.")
    else:
        print("[4/7] Skipping comment collection (--skip-comments).")

    # ------------------------------------------------------------------ #
    # Step 5 — Thumbnail classification
    # ------------------------------------------------------------------ #
    if not skip_vision:
        print("[5/7] Downloading and classifying thumbnails...")
        thumb_paths = collector.download_thumbnails(all_videos, THUMB_DIR)
        styles = vision.classify_thumbnails(thumb_paths, project)
        for v in all_videos:
            v["thumbnail_style"] = styles.get(v["video_id"], "unknown")
        print(f"  Classified {len(styles)} thumbnails.")
    else:
        print("[5/7] Skipping thumbnail classification (--skip-vision).")

    # ------------------------------------------------------------------ #
    # Step 6 — Store
    # ------------------------------------------------------------------ #
    print("[6/7] Storing data in SQLite...")
    prev_snapshot = db.get_prev_snapshot(DB_PATH, week_label)

    for ch in channels.values():
        db.upsert_channel(DB_PATH, ch)
    for v in all_videos:
        db.upsert_video(DB_PATH, v)
    db.insert_comments(DB_PATH, comments)
    db.save_snapshot(DB_PATH, week_label, channels)

    # ------------------------------------------------------------------ #
    # Step 7 — Analyse + generate deck
    # ------------------------------------------------------------------ #
    print("[7/7] Running analysis and generating slide deck...")

    eng = analyzer.engagement_rate(all_videos)
    dur_eng = analyzer.duration_engagement(all_videos, eng)
    velocity_list = analyzer.view_velocity(all_videos)
    topics = analyzer.trending_topics(all_videos)
    title_words = analyzer.top_title_words(all_videos)
    sentiment = analyzer.comment_sentiment(comments)
    timing = analyzer.publish_timing(all_videos)
    evergreen = analyzer.evergreen_split(all_videos)
    gaps = analyzer.content_gaps(all_videos, PROJECT_ROOT / "outputs" / "videos_pl")

    results = {
        "channels": channels,
        "videos": all_videos,
        "comments": comments,
        "week_label": week_label,
        "prev_snapshot": prev_snapshot,
        "trending_topics": topics,
        "view_velocity": velocity_list,
        "engagement": eng,
        "duration_engagement": dur_eng,
        "gaps": gaps,
        "sentiment": sentiment,
        "timing": timing,
        "evergreen": evergreen,
        "title_words": title_words,
    }

    pptx_path = slide_builder.build_deck(results, week_label, INTEL_DIR)

    signals_path = _write_tag_signals(results, week_label, INTEL_DIR)
    print(f"  Tag signals sidecar: {signals_path.name}")

    # ------------------------------------------------------------------ #
    # Cost log
    # ------------------------------------------------------------------ #
    log_cost("intelligence", "niche_intel", {
        "week_label": week_label,
        "channels_analyzed": len(channels),
        "videos_collected": len(all_videos),
        "comments_collected": len(comments),
        "thumbnails_classified": len(all_videos) if not skip_vision else 0,
        "output": str(pptx_path),
    })

    print(f"\n{'='*60}")
    print(f"  Done!")
    print(f"  Deck    : {pptx_path}")
    print(f"  Signals : {signals_path}")
    print(f"  DB      : {DB_PATH}")
    print(f"{'='*60}\n")


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #

def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Agent 11: Weekly YouTube Niche Intelligence")
    p.add_argument("--skip-vision", action="store_true",
                   help="Skip Gemini thumbnail classification")
    p.add_argument("--skip-comments", action="store_true",
                   help="Skip YouTube comment collection")
    p.add_argument("--days", type=int, default=30,
                   help="Look-back window in days (default: 30)")
    return p.parse_args()


def main():
    args = _parse_args()
    run(
        skip_vision=args.skip_vision,
        skip_comments=args.skip_comments,
        days=args.days,
    )


if __name__ == "__main__":
    main()
